TebLocalPlannerROS:
  odom_topic: agv1/odom
  # Timed Elastic Band
  teb_autosize: True
  # Robot Configuration
  wheelbase: 0.0
  max_vel_x: 0.8
  max_vel_theta: 2.8        # Maximum angular velocity of the robot in radians/sec
  max_vel_x_backwards: 0.3  # Maximum absolute translational velocity of the robot while driving backwards in meters/sec
  acc_lim_x: 0.3
  acc_lim_y: 0.6
  acc_lim_theta: 1.5

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.32
  is_footprint_dynamic: false

  # Goal Tolerance
  xy_goal_tolerance: 0.45
  yaw_goal_tolerance: 0.18
  free_goal_vel: false

  # Trajectory Configuration
  min_samples: 3
  dt_ref: 0.3
  dt_hysteresis: 0.03
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 1.0
  feasibility_check_no_poses: 1
  exact_arc_length: true

  # Obstacles
  min_obstacle_dist: 0.30   # Minimum desired separation from obstacles in meters
  inflation_dist: 0.4
  include_dynamic_obstacles: true
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 10
  costmap_converter_spin_thread: true
  costmap_converter_rate: 6

  dynamic_obstacle_inflation_dist: 0.65
  obstacle_association_force_inclusion_factor: 2.0
  obstacle_association_cutoff_factor: 4.0
  selection_viapoint_cost_scale: true

  # Optimization Parameters
  penalty_epsilon: 0.15

  # Parallel Planning
  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  visualize_hc_graph: true


#TrajectoryPlannerROS:
#  # Trajectory Rollout and Dynamic Window
#  max_vel_x: 0.6
#  min_vel_x: 0.1
#  max_vel_theta: 0.5
#  min_in_place_vel_theta: 0.1
#  escape_vel: -0.2
#
#  acc_lim_theta: 0.25
#  acc_lim_x: 0.25
#  acc_lim_y: 0.25
#
#  sim_time: 5
#  meter_scoring: True
#  holonomic_robot: False
