obstacle_range: 5.0
raytrace_range: 6.0
footprint: [ [0.28, 0.28], [0.28, -0.28], [-0.28, -0.28], [-0.28, 0.28] ]
footprint_padding: 0.01

#global_frame: map
robot_base_frame: agv1/base_link
subscribe_to_updates: true
always_send_full_costmap: true
transform_tolerance: 1.0

resolution: 0.1

inflation_layer:
    enabled: true
    inflation_radius: 0.8

static_layer:
    enable: true
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    enable: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: agv1/hokuyo, data_type: LaserScan, topic: agv1/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, inf_is_valid: true}

#plugins:
#    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
#    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}