global_costmap:
  global_frame: map
  robot_base_frame: agv1/base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  width: 80
  height: 80
  origin_x: -7.5
  origin_y: -7.5
  rolling_window: false
  track_unknown_space: true
  resolution: 0.1

  plugins:
    - {name: static_layer,                  type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,                type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,               type: "costmap_2d::InflationLayer"}