global_costmap:
   # global_frame: map                               # Coordinate frame tied to occupancy grid map
   # robot_base_frame: agv1/base_link             # Defines coordinate tied to robot

   # Update rate
   update_frequency: 5.0
   publish_frequency: 5.0

   # Width and height of the map, in meters
   width: 80.0
   height: 80.0
   static_map: false
   resolution: 0.05                                # Resolution of the map, higher in smaller maps
   static_map: true
   rolling_window: false                           # Keep the costmap centered on the robot when it is moving around the world
   inflation_radius: 0.2
